function Y7(){}
function c8(){}
function cnb(){}
function Omb(){}
function Umb(){}
function Zmb(){}
function k3d(){}
function e3d(){}
function e8(b){this.b=b}
function enb(b){this.b=b}
function Wmb(b){this.b=b}
function _mb(b){this.b=b}
function jV(b){b.c.$e(nM(b.b.b))}
function VH(b,c,d){return new _7(b,c,d)}
function m3d(){h3d=new k3d;r6c((o6c(),n6c),40);!!$stats&&$stats(g7c(sjg,qcf,-1,-1));h3d.Se();!!$stats&&$stats(g7c(sjg,Byf,-1,-1))}
function _7(b,c,d){eX.call(this,b,c);this.d=d;lhd(this.j,15).Tc(this);lhd(lhd(this.j,15).Uc(),3).b=lhd(this.d,16).Qc();Jwb(lhd(this.j,15).d,_4())}
function j3d(){var b,d,e;while(f3d){d=w4c;e=f3d;f3d=f3d.c;!f3d&&(g3d=null);if(!d){jV(e.b)}else{try{jV(e.b)}catch(b){b=EQd(b);if(!ohd(b,209))throw b}}}}
function nM(b){var c;!b.t&&(b.t=(c=VH((!b.Gc&&(b.Gc=new die),b.Gc),(!b.K&&(b.K=new Rmb),b.K),(!b.s&&(b.s=new l8),b.s),!b.Fc&&(b.Fc=(new Wge).ef(new Fge,new Jge))),c.Mc(),c));return b.t}
function $7(b,c){var d,e,f,g;g=new yme;f=new o$e;for(e=0;e<c.c;++e){f.ml(v2f+(e+1),lhd((wXe(e,c.c),c.b[e]),1))}d=MVe(f);g.M[z7e]=d;g.M[A7e]=s7c()+ojg;g.M[C7e]=D7e;lCe(g.M,E7e,(WOe(),WOe(),VOe));lCe(g.M,YBf,VOe);$wnd.isc.RPCManager.addClassProperties({promptStyle:(gze(),fze).Rk()});pBe();$wnd.isc.RPCManager.defaultPrompt=pjg;$wnd.isc.RPCManager.showPrompt=true;eue(g,new e8(b))}
function Rmb(){var b,e,f,g;this.c=new Q3c;b=new ENe;Egb(b)?(e=b.cd(),e.setProperty(M6e,J6e),undefined):(b.o[M6e]=J6e,undefined);Jgb(b,l8e,JQe(2));this.f=new KNe;Fgb(this.f,jyf,GIf,true);Hhb(this.f,uZf);Fgb(this.f,Vbf,IIf,true);f=this.f.rd();f.disable();CNe(b,this.f);this.e=new KNe;Fgb(this.e,jyf,kAf,true);Hhb(this.e,qjg);Fgb(this.e,Vbf,Uif,true);CNe(b,this.e);this.b=new KNe;Fgb(this.b,jyf,DCf,true);Hhb(this.b,nLf);Fgb(this.b,Vbf,Qaf,true);g=this.b.rd();g.disable();CNe(b,this.b);this.d=new Owb(this);ltb(this.c,Zgd(eQd,{267:1,317:1},137,[b,this.d]));rhb(this.f,new Wmb(this));rhb(this.b,new _mb(this));rhb(this.e,new enb(this));Fwb(this.d)}
var zjg='AsyncLoader40',tjg='JournalPresenter',ujg='JournalPresenter$1',ojg='JournalPresenterServlet?method=submitJournalForApproval&type=RPC',vjg='JournalView',wjg='JournalView$1',xjg='JournalView$2',yjg='JournalView$3',qjg='Print Journal Details',pjg='Submitting journals for approval...',rjg='Venice/JournalReportLauncherServlet?journalGroupId=',sjg='runCallbacks40';_=_7.prototype=Y7.prototype=new JW;_.gC=function a8(){return xld};_.Oc=function b8(){cie(this.g,this,new ble((k_c(),i_c),this))};_.cM={35:1,87:1,304:1};_=e8.prototype=c8.prototype=new nH;_.Pc=function f8(b,c,d){var e,f;e=c.tM==T0e||c.cM&&!!c.cM[1]?c.tS():c.toString?c.toString():D6e;if(e.indexOf(qdf)==0){Kwb(lhd(lhd(this.b.j,15),17).d);$wnd.isc.say(cIf)}else{f=WRe(e,I7e,0);f.length>1?UCe(f[1],null):UCe(gAf,null)}pBe();$wnd.isc.RPCManager.defaultPrompt=mCf;$wnd.isc.RPCManager.showPrompt=false};_.gC=function g8(){return uld};_.cM={};_.b=null;_=Rmb.prototype=Omb.prototype=new uY;_.Uc=function Smb(){return this.c};_.gC=function Tmb(){return rnd};_.cM={15:1,17:1};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_=Wmb.prototype=Umb.prototype=new nH;_.gC=function Xmb(){return ond};_.Vc=function Ymb(b){var c,d,e,f,g,i;e=(f=this.b.d.f.rd(),g=f.getSelection(),_ib(g));d=new bZe;for(c=0;c<e.length;++c){QYe(d,(i=e[c].M[aCf],i===undefined||i==null?null:String(i)))}$7(lhd(this.b.A,35),d)};_.cM={287:1,319:1};_.b=null;_=_mb.prototype=Zmb.prototype=new nH;_.gC=function anb(){return pnd};_.Vc=function bnb(b){var c,d,e,f,g,i;e=(f=this.b.d.f.rd(),g=f.getSelection(),_ib(g));d=(i=e[0].M[aCf],i===undefined||i==null?null:String(i));c=s7c();c.indexOf(FDf)!=-1&&(c=GDf);c.indexOf(HDf)!=-1&&(c=c.substr(0,c.indexOf(HDf)-0));$wnd.open(c+rjg+d,_Cf,null)};_.cM={287:1,319:1};_.b=null;_=enb.prototype=cnb.prototype=new nH;_.gC=function fnb(){return qnd};_.Vc=function gnb(b){Y0c(this.b.d)};_.cM={287:1,319:1};_.b=null;_=k3d.prototype=e3d.prototype=new nH;_.gC=function l3d(){return aJd};_.Se=function p3d(){j3d()};_.cM={};var xld=lPe(anf,tjg),uld=lPe(anf,ujg),rnd=lPe(hzf,vjg),ond=lPe(hzf,wjg),pnd=lPe(hzf,xjg),qnd=lPe(hzf,yjg),aJd=lPe(Fsf,zjg);$entry(m3d)();