function EYc(){}
function UZc(){}
function j$c(){}
function r$c(){}
function p$c(){}
function w$c(){}
function u$c(){}
function z$c(){}
function XTd(){}
function RTd(){}
function B$c(b){this.b=b}
function QZc(){KZc.call(this)}
function RP(b){b.c.$e(XM(b.b.b))}
function zI(b,c,d){return new WZc(b,c,d)}
function WZc(b,c,d){eX.call(this,b,c);this.d=d;lhd(this.j,270).Tc(this)}
function ZTd(){UTd=new XTd;r6c((o6c(),n6c),14);!!$stats&&$stats(g7c(gOf,qcf,-1,-1));UTd.Se();!!$stats&&$stats(g7c(gOf,Byf,-1,-1))}
function WTd(){var b,d,e;while(STd){d=w4c;e=STd;STd=STd.c;!STd&&(TTd=null);if(!d){RP(e.b)}else{try{RP(e.b)}catch(b){b=EQd(b);if(!ohd(b,209))throw b}}}}
function XM(b){var c;!b.xc&&(b.xc=(c=zI((!b.Gc&&(b.Gc=new die),b.Gc),(!b.yc&&(b.yc=new m$c),b.yc),(!b.wc&&(b.wc=new b$c),b.wc),!b.Fc&&(b.Fc=(new Wge).ef(new Fge,new Jge))),c.Mc(),c));return b.xc}
function DYc(){var b,c,d,e,f,g,i,j;if(BYc){return BYc}else{BYc=new QZc;QYc(BYc,KNf,LNf,false);g=new hne;g.M[MNf]=(rve(),nve).b;g.M[NNf]=(Fve(),Bve).b;b=new hne;b.M[MNf]=lve.b;b.M[NNf]=Bve.b;j=new hne;j.M[MNf]=pve.b;j.M[NNf]=Bve.b;i=new hne;i.M[MNf]=ove.b;i.M[NNf]=Bve.b;TYc(BYc,ONf,Zgd(CPd,{267:1,317:1},105,[g,b,j,i]));c=new qoe(PNf,QNf);lCe(c.M,Wxf,(WOe(),WOe(),VOe));d=new qoe(RNf,SNf);d.M[TNf]=UNf;e=new qoe(VNf,WNf);f=new qoe(XNf,YNf);qZc(BYc,Zgd(APd,{267:1,317:1},103,[c,d,e,f]));QYc(BYc,ZNf,s7c()+$Nf,false);QYc(BYc,_Nf,s7c()+aOf,false);return BYc}}
function m$c(){var b,c,d,e,i,n,q,t,w,x,y,z,A;this.b=new utb;d=new nDe;Fgb(d,_7e,(Oye(),Iye).b,true);Jgb(d,l8e,JQe(2));Egb(d)?(i=d.cd(),i.setProperty(M6e,J6e),undefined):(d.o[M6e]=J6e,undefined);Egb(d)?(n=d.cd(),n.setProperty(I6e,20),undefined):(d.o[I6e]=20,undefined);Egb(d)?(q=d.cd(),q.setProperty(Y7e,bOf),undefined):(d.o[Y7e]=bOf,undefined);c=new bDe(cOf);rhb(c,new r$c);e=new ENe;b=new KNe;Egb(b)?(t=b.cd(),t.setProperty(jyf,kyf),undefined):(b.o[jyf]=kyf,undefined);Egb(b)?(w=b.cd(),w.setProperty(lyf,Fgf),undefined):(b.o[lyf]=Fgf,undefined);rhb(b,new B$c(this));CNe(e,b);ltb(this.b,Zgd(eQd,{267:1,317:1},137,[d,c,e,(this.c=new Xib,Khb(this.c),Ghb(this.c),Lgb(this.c,ezf,(WOe(),WOe(),VOe),true),Igb(this.c,byf,0,true),x=new gKe(PNf),y=new gKe(RNf),z=new gKe(VNf),A=new gKe(XNf),Hgb(this.c,ayf,Zgd(jQd,{267:1,317:1},190,[x,y,z,A]),true),Lgb(this.c,qyf,VOe,true),Lgb(this.c,vyf,VOe,true),Kgb(this.c,_xf,OYc(DYc())),Lgb(this.c,pyf,VOe,false),Igb(this.c,byf,0,true),Lgb(this.c,pyf,VOe,false),Lgb(this.c,ryf,VOe,true),Lgb(this.c,dOf,VOe,true),this.c)]))}
var LNf='/response/data/recordlist/*',bOf='<span style="font-size:14px;font-weight:bold;">Test Rest Data Source<\/span>',pOf='AsyncLoader14',eOf='DATA',QNf='Data 1',SNf='Data 2',WNf='Data 3',YNf='Data 4',cOf='Test RPC',iOf='TestRestDataSourceData$1',jOf='TestRestDataSourcePresenter',aOf='TestRestDataSourceServlet?method=add',$Nf='TestRestDataSourceServlet?method=fetch',fOf='TestRestDataSourceServlet?method=rpc',lOf='TestRestDataSourceView',mOf='TestRestDataSourceView$1',nOf='TestRestDataSourceView$1$1',oOf='TestRestDataSourceView$2',hOf='com.gdn.venice.client.app.testrestdatasource.data.',kOf='com.gdn.venice.client.app.testrestdatasource.view.',PNf='data1',RNf='data2',UNf='data2/name',VNf='data3',XNf='data4',gOf='runCallbacks14',TNf='valueXPath';var BYc=null;_=QZc.prototype=EYc.prototype=new FYc;_.gC=function RZc(){return lFd};_.qe=function SZc(b){var c;return c=this.rd(),c.__transformRequest(b.cd())};_.re=function TZc(b,c,d){var e;e=this.rd();e.__transformResponse(b.cd(),c.cd(),d)};_.cM={87:1,217:1,314:1};_=WZc.prototype=UZc.prototype=new JW;_.gC=function XZc(){return oFd};_.Oc=function YZc(){cie(this.g,this,new ble((k_c(),i_c),this))};_.cM={87:1,304:1};_=m$c.prototype=j$c.prototype=new uY;_.Uc=function n$c(){return this.b};_.gC=function o$c(){return sFd};_.cM={270:1};_.b=null;_.c=null;_=r$c.prototype=p$c.prototype=new nH;_.gC=function s$c(){return qFd};_.Vc=function t$c(b){var c;c=new yme;c.M[z7e]=eOf;c.M[A7e]=s7c()+fOf;c.M[C7e]=D7e;lCe(c.M,E7e,(WOe(),WOe(),VOe));lCe(c.M,F7e,UOe);eue(c,new w$c)};_.cM={287:1,319:1};_=w$c.prototype=u$c.prototype=new nH;_.Pc=function x$c(b,c,d){$wnd.isc.say(gAf)};_.gC=function y$c(){return pFd};_.cM={};_=B$c.prototype=z$c.prototype=new nH;_.gC=function C$c(){return rFd};_.Vc=function D$c(b){var c;c=this.b.c.rd();c.startEditingNew()};_.cM={287:1,319:1};_.b=null;_=XTd.prototype=RTd.prototype=new nH;_.gC=function YTd(){return vHd};_.Se=function aUd(){WTd()};_.cM={};var lFd=lPe(hOf,iOf),oFd=lPe(Lof,jOf),sFd=lPe(kOf,lOf),qFd=lPe(kOf,mOf),pFd=lPe(kOf,nOf),rFd=lPe(kOf,oOf),vHd=lPe(Fsf,pOf);$entry(ZTd)();