function fOc(){}
function SPc(){}
function YPc(){}
function LUd(){}
function FUd(){}
function lQ(b){b.c.$e(UM(b.b.b))}
function $Pc(){pgb();Xib.call(this)}
function hOc(b,c,d){eX.call(this,b,c);this.d=d;lhd(this.j,260).Tc(this);lhd(lhd(this.j,260).Uc(),3).b=lhd(this.d,261).Qc()}
function NUd(){IUd=new LUd;r6c((o6c(),n6c),16);!!$stats&&$stats(g7c(UOf,qcf,-1,-1));IUd.Se();!!$stats&&$stats(g7c(UOf,Byf,-1,-1))}
function KUd(){var b,d,e;while(GUd){d=w4c;e=GUd;GUd=GUd.c;!GUd&&(HUd=null);if(!d){lQ(e.b)}else{try{lQ(e.b)}catch(b){b=EQd(b);if(!ohd(b,209))throw b}}}}
function UM(b){var c;!b.nc&&(b.nc=(c=new hOc((!b.Gc&&(b.Gc=new die),b.Gc),(!b.tc&&(b.tc=new VPc),b.tc),(!b.mc&&(b.mc=new oOc),b.mc)),c.Mc(),c));return b.nc}
function MNc(){var b,c,d;if(KNc){return KNc}else{KNc=new tZc;KNc.pe(MOf);b=new qoe(w6e,aMf);lCe(b.M,Wxf,(WOe(),WOe(),VOe));d=new qoe(dzf,NOf);c=new qoe(Ubf,OOf);qZc(KNc,Zgd(APd,{267:1,317:1},103,[b,d,c]));KNc.oe(POf);RYc(KNc,QOf,VOe,false);return KNc}}
function VPc(){var b,c,d,e,f,g,i,j;this.b=new Q3c;ltb(this.b,Zgd(eQd,{267:1,317:1},137,[(e=new $Pc,Egb(e)?(g=e.cd(),g.setProperty(M6e,J6e),undefined):(e.o[M6e]=J6e,undefined),Egb(e)?(i=e.cd(),i.setProperty(I6e,J6e),undefined):(e.o[I6e]=J6e,undefined),Lgb(e,ezf,(WOe(),WOe(),VOe),true),Lgb(e,RMf,VOe,true),Iib(e,VOe),Egb(e)?(j=e.cd(),j.setProperty(byf,0),undefined):(e.o[byf]=0,undefined),b=new jKe(w6e,aMf,100),f=new iKe(dzf,NOf),c=new iKe(Ubf,OOf),d=new jKe(ROf,SOf,200),Egb(e)?Tgb(e,ayf,wBe(Zgd(jQd,{267:1,317:1},190,[b,f,c,d]))):(e.o[ayf]=wBe(Zgd(jQd,{267:1,317:1},190,[b,f,c,d])),undefined),Lgb(e,qyf,VOe,true),Lgb(e,vyf,VOe,true),Kgb(e,_xf,OYc(MNc())),Lgb(e,pyf,VOe,false),Egb(e)?undefined:(e.o[fIf]=dzf,undefined),Ggb(e,(axe(),Zwe)),Lgb(e,ryf,VOe,true),Lgb(e,dOf,VOe,true),e)]))}
var MOf='/tasklaunchpad/tasks/task',ZOf='AsyncLoader16',SOf='Start',VOf='TaskLaunchpadPresenter',XOf='TaskLaunchpadView',YOf='TaskLaunchpadView$1',TOf='[SKIN]/icons/play.png',POf='ds/test_data/tasklaunchpad.data.xml',UOf='runCallbacks16',ROf='startField';var KNc=null;_=hOc.prototype=fOc.prototype=new JW;_.gC=function iOc(){return yDd};_.Oc=function jOc(){cie(this.g,this,new ble((k_c(),i_c),this))};_.cM={87:1,304:1};_=VPc.prototype=SPc.prototype=new uY;_.Uc=function WPc(){return this.b};_.gC=function XPc(){return NDd};_.cM={260:1};_.b=null;_=$Pc.prototype=YPc.prototype=new Vfb;_.Dd=function _Pc(b,c){var d,e,i,n,q,t;e=oib(this,c.b);if(LRe(e,ROf)){d=new IDe;Egb(d)?(i=d.cd(),i.setProperty(I6e,18),undefined):(d.o[I6e]=18,undefined);Egb(d)?(n=d.cd(),n.setProperty(M6e,65),undefined):(d.o[M6e]=65,undefined);Egb(d)?(q=d.cd(),q.setProperty(jyf,TOf),undefined):(d.o[jyf]=TOf,undefined);Egb(d)?(t=d.cd(),t.setProperty(Vbf,SOf),undefined):(d.o[Vbf]=SOf,undefined);return d}else{return null}};_.gC=function aQc(){return MDd};_.cM={69:1,86:1,87:1,91:1,93:1,94:1,95:1,136:1,137:1,138:1,139:1,140:1,141:1,142:1,143:1,144:1,145:1,146:1,147:1,148:1,149:1,150:1,151:1,152:1,153:1,154:1,155:1,156:1,157:1,158:1,159:1,160:1,161:1,162:1,163:1,164:1,165:1,166:1,167:1,168:1,169:1,192:1,195:1,196:1,197:1};_=LUd.prototype=FUd.prototype=new nH;_.gC=function MUd(){return BHd};_.Se=function QUd(){KUd()};_.cM={};var yDd=lPe(Aof,VOf),NDd=lPe(WOf,XOf),MDd=lPe(WOf,YOf),BHd=lPe(Fsf,ZOf);$entry(NUd)();