function DYc(){}
function TZc(){}
function i$c(){}
function q$c(){}
function o$c(){}
function v$c(){}
function t$c(){}
function y$c(){}
function GTd(){}
function ATd(){}
function A$c(b){this.b=b}
function PZc(){JZc.call(this)}
function QP(b){b.c.df(WM(b.b.b))}
function yI(b,c,d){return new VZc(b,c,d)}
function VZc(b,c,d){dX.call(this,b,c);this.d=d;Xgd(this.j,270).Tc(this)}
function ITd(){DTd=new GTd;p6c((m6c(),l6c),14);!!$stats&&$stats(e7c(vPf,Wcf,-1,-1));DTd.Re();!!$stats&&$stats(e7c(vPf,Qzf,-1,-1))}
function FTd(){var b,d,e;while(BTd){d=v4c;e=BTd;BTd=BTd.c;!BTd&&(CTd=null);if(!d){QP(e.b)}else{try{QP(e.b)}catch(b){b=nQd(b);if(!$gd(b,209))throw b}}}}
function WM(b){var c;!b.xc&&(b.xc=(c=yI((!b.Gc&&(b.Gc=new Hie),b.Gc),(!b.yc&&(b.yc=new l$c),b.yc),(!b.wc&&(b.wc=new a$c),b.wc),!b.Fc&&(b.Fc=(new yhe).lf(new hhe,new lhe))),c.Mc(),c));return b.xc}
function CYc(){var b,c,d,e,f,g,i,j;if(AYc){return AYc}else{AYc=new PZc;PYc(AYc,ZOf,$Of,false);g=new Lne;g.M[_Of]=(Vve(),Rve).b;g.M[aPf]=(hwe(),dwe).b;b=new Lne;b.M[_Of]=Pve.b;b.M[aPf]=dwe.b;j=new Lne;j.M[_Of]=Tve.b;j.M[aPf]=dwe.b;i=new Lne;i.M[_Of]=Sve.b;i.M[aPf]=dwe.b;SYc(AYc,bPf,Jgd(lPd,{267:1,316:1},105,[g,b,j,i]));c=new Uoe(cPf,dPf);PCe(c.M,jzf,(yPe(),yPe(),xPe));d=new Uoe(ePf,fPf);d.M[gPf]=hPf;e=new Uoe(iPf,jPf);f=new Uoe(kPf,lPf);pZc(AYc,Jgd(jPd,{267:1,316:1},103,[c,d,e,f]));PYc(AYc,mPf,q7c()+nPf,false);PYc(AYc,oPf,q7c()+pPf,false);return AYc}}
function l$c(){var b,c,d,e,i,n,q,t,w,x,y,z,A;this.b=new ttb;d=new RDe;Egb(d,F8e,(qze(),kze).b,true);Igb(d,R8e,lRe(2));Dgb(d)?(i=d.cd(),i.setProperty(p7e,m7e),undefined):(d.o[p7e]=m7e,undefined);Dgb(d)?(n=d.cd(),n.setProperty(l7e,20),undefined):(d.o[l7e]=20,undefined);Dgb(d)?(q=d.cd(),q.setProperty(C8e,qPf),undefined):(d.o[C8e]=qPf,undefined);c=new FDe(rPf);qhb(c,new q$c);e=new gOe;b=new mOe;Dgb(b)?(t=b.cd(),t.setProperty(yzf,zzf),undefined):(b.o[yzf]=zzf,undefined);Dgb(b)?(w=b.cd(),w.setProperty(Azf,Whf),undefined):(b.o[Azf]=Whf,undefined);qhb(b,new A$c(this));eOe(e,b);ktb(this.b,Jgd(PPd,{267:1,316:1},137,[d,c,e,(this.c=new Wib,Jhb(this.c),Fhb(this.c),Kgb(this.c,tAf,(yPe(),yPe(),xPe),true),Hgb(this.c,qzf,0,true),x=new KKe(cPf),y=new KKe(ePf),z=new KKe(iPf),A=new KKe(kPf),Ggb(this.c,pzf,Jgd(UPd,{267:1,316:1},190,[x,y,z,A]),true),Kgb(this.c,Fzf,xPe,true),Kgb(this.c,Kzf,xPe,true),Jgb(this.c,ozf,NYc(CYc())),Kgb(this.c,Ezf,xPe,false),Hgb(this.c,qzf,0,true),Kgb(this.c,Ezf,xPe,false),Kgb(this.c,Gzf,xPe,true),Kgb(this.c,sPf,xPe,true),this.c)]))}
var $Of='/response/data/recordlist/*',qPf='<span style="font-size:14px;font-weight:bold;">Test Rest Data Source<\/span>',EPf='AsyncLoader14',tPf='DATA',dPf='Data 1',fPf='Data 2',jPf='Data 3',lPf='Data 4',rPf='Test RPC',xPf='TestRestDataSourceData$1',yPf='TestRestDataSourcePresenter',pPf='TestRestDataSourceServlet?method=add',nPf='TestRestDataSourceServlet?method=fetch',uPf='TestRestDataSourceServlet?method=rpc',APf='TestRestDataSourceView',BPf='TestRestDataSourceView$1',CPf='TestRestDataSourceView$1$1',DPf='TestRestDataSourceView$2',wPf='com.gdn.venice.client.app.testrestdatasource.data.',zPf='com.gdn.venice.client.app.testrestdatasource.view.',cPf='data1',ePf='data2',hPf='data2/name',iPf='data3',kPf='data4',vPf='runCallbacks14',gPf='valueXPath';var AYc=null;_=PZc.prototype=DYc.prototype=new EYc;_.gC=function QZc(){return XEd};_.qe=function RZc(b){var c;return c=this.rd(),c.__transformRequest(b.cd())};_.re=function SZc(b,c,d){var e;e=this.rd();e.__transformResponse(b.cd(),c.cd(),d)};_.cM={87:1,217:1,313:1};_=VZc.prototype=TZc.prototype=new IW;_.gC=function WZc(){return $Ed};_.Oc=function XZc(){Gie(this.g,this,new Fle((j_c(),h_c),this))};_.cM={87:1,303:1};_=l$c.prototype=i$c.prototype=new tY;_.Uc=function m$c(){return this.b};_.gC=function n$c(){return cFd};_.cM={270:1};_.b=null;_.c=null;_=q$c.prototype=o$c.prototype=new mH;_.gC=function r$c(){return aFd};_.Vc=function s$c(b){var c;c=new ane;c.M[c8e]=tPf;c.M[d8e]=q7c()+uPf;c.M[f8e]=g8e;PCe(c.M,h8e,(yPe(),yPe(),xPe));PCe(c.M,i8e,wPe);Iue(c,new v$c)};_.cM={286:1,318:1};_=v$c.prototype=t$c.prototype=new mH;_.Pc=function w$c(b,c,d){$wnd.isc.say(vBf)};_.gC=function x$c(){return _Ed};_.cM={};_=A$c.prototype=y$c.prototype=new mH;_.gC=function B$c(){return bFd};_.Vc=function C$c(b){var c;c=this.b.c.rd();c.startEditingNew()};_.cM={286:1,318:1};_.b=null;_=GTd.prototype=ATd.prototype=new mH;_.gC=function HTd(){return bHd};_.Re=function LTd(){FTd()};_.cM={};var XEd=PPe(wPf,xPf),$Ed=PPe(_pf,yPf),cFd=PPe(zPf,APf),aFd=PPe(zPf,BPf),_Ed=PPe(zPf,CPf),bFd=PPe(zPf,DPf),bHd=PPe(Rtf,EPf);$entry(ITd)();