function bOc(){}
function OPc(){}
function UPc(){}
function iUd(){}
function cUd(){}
function hQ(b){b.c.We(QM(b.b.b))}
function WPc(){lgb();Tib.call(this)}
function dOc(b,c,d){aX.call(this,b,c);this.d=d;Ogd(this.j,260).Tc(this);Ogd(Ogd(this.j,260).Uc(),3).b=Ogd(this.d,261).Qc()}
function kUd(){fUd=new iUd;n6c((k6c(),j6c),16);!!$stats&&$stats(c7c(nOf,Nbf,-1,-1));fUd.Oe();!!$stats&&$stats(c7c(nOf,Wxf,-1,-1))}
function hUd(){var b,d,e;while(dUd){d=s4c;e=dUd;dUd=dUd.c;!dUd&&(eUd=null);if(!d){hQ(e.b)}else{try{hQ(e.b)}catch(b){b=bQd(b);if(!Rgd(b,209))throw b}}}}
function QM(b){var c;!b.nc&&(b.nc=(c=new dOc((!b.Gc&&(b.Gc=new Ahe),b.Gc),(!b.tc&&(b.tc=new RPc),b.tc),(!b.mc&&(b.mc=new kOc),b.mc)),c.Mc(),c));return b.nc}
function INc(){var b,c,d;if(GNc){return GNc}else{GNc=new pZc;GNc.pe(fOf);b=new Nne(T5e,vLf);IBe(b.M,pxf,(rOe(),rOe(),qOe));d=new Nne(yyf,gOf);c=new Nne(pbf,hOf);mZc(GNc,Agd(ZOd,{267:1,317:1},103,[b,d,c]));GNc.oe(iOf);NYc(GNc,jOf,qOe,false);return GNc}}
function RPc(){var b,c,d,e,f,g,i,j;this.b=new M3c;htb(this.b,Agd(DPd,{267:1,317:1},137,[(e=new WPc,Agb(e)?(g=e.cd(),g.setProperty(h6e,e6e),undefined):(e.o[h6e]=e6e,undefined),Agb(e)?(i=e.cd(),i.setProperty(d6e,e6e),undefined):(e.o[d6e]=e6e,undefined),Hgb(e,zyf,(rOe(),rOe(),qOe),true),Hgb(e,kMf,qOe,true),Eib(e,qOe),Agb(e)?(j=e.cd(),j.setProperty(wxf,0),undefined):(e.o[wxf]=0,undefined),b=new GJe(T5e,vLf,100),f=new FJe(yyf,gOf),c=new FJe(pbf,hOf),d=new GJe(kOf,lOf,200),Agb(e)?Pgb(e,vxf,TAe(Agd(IPd,{267:1,317:1},190,[b,f,c,d]))):(e.o[vxf]=TAe(Agd(IPd,{267:1,317:1},190,[b,f,c,d])),undefined),Hgb(e,Lxf,qOe,true),Hgb(e,Qxf,qOe,true),Ggb(e,uxf,KYc(INc())),Hgb(e,Kxf,qOe,false),Agb(e)?undefined:(e.o[AHf]=yyf,undefined),Cgb(e,(xwe(),uwe)),Hgb(e,Mxf,qOe,true),Hgb(e,yNf,qOe,true),e)]))}
var fOf='/tasklaunchpad/tasks/task',sOf='AsyncLoader16',lOf='Start',oOf='TaskLaunchpadPresenter',qOf='TaskLaunchpadView',rOf='TaskLaunchpadView$1',mOf='[SKIN]/icons/play.png',iOf='ds/test_data/tasklaunchpad.data.xml',nOf='runCallbacks16',kOf='startField';var GNc=null;_=dOc.prototype=bOc.prototype=new FW;_.gC=function eOc(){return _Cd};_.Oc=function fOc(){zhe(this.g,this,new yke((g_c(),e_c),this))};_.cM={87:1,304:1};_=RPc.prototype=OPc.prototype=new qY;_.Uc=function SPc(){return this.b};_.gC=function TPc(){return oDd};_.cM={260:1};_.b=null;_=WPc.prototype=UPc.prototype=new Rfb;_.Dd=function XPc(b,c){var d,e,i,n,q,t;e=kib(this,c.b);if(gRe(e,kOf)){d=new dDe;Agb(d)?(i=d.cd(),i.setProperty(d6e,18),undefined):(d.o[d6e]=18,undefined);Agb(d)?(n=d.cd(),n.setProperty(h6e,65),undefined):(d.o[h6e]=65,undefined);Agb(d)?(q=d.cd(),q.setProperty(Exf,mOf),undefined):(d.o[Exf]=mOf,undefined);Agb(d)?(t=d.cd(),t.setProperty(qbf,lOf),undefined):(d.o[qbf]=lOf,undefined);return d}else{return null}};_.gC=function YPc(){return nDd};_.cM={69:1,86:1,87:1,91:1,93:1,94:1,95:1,136:1,137:1,138:1,139:1,140:1,141:1,142:1,143:1,144:1,145:1,146:1,147:1,148:1,149:1,150:1,151:1,152:1,153:1,154:1,155:1,156:1,157:1,158:1,159:1,160:1,161:1,162:1,163:1,164:1,165:1,166:1,167:1,168:1,169:1,192:1,195:1,196:1,197:1};_=iUd.prototype=cUd.prototype=new jH;_.gC=function jUd(){return _Gd};_.Oe=function nUd(){hUd()};_.cM={};var _Cd=IOe(Znf,oOf),oDd=IOe(pOf,qOf),nDd=IOe(pOf,rOf),_Gd=IOe(_rf,sOf);$entry(kUd)();