function AYc(){}
function QZc(){}
function f$c(){}
function n$c(){}
function l$c(){}
function s$c(){}
function q$c(){}
function v$c(){}
function wTd(){}
function qTd(){}
function x$c(b){this.b=b}
function MZc(){GZc.call(this)}
function NP(b){b.c.We(TM(b.b.b))}
function vI(b,c,d){return new SZc(b,c,d)}
function SZc(b,c,d){aX.call(this,b,c);this.d=d;Qgd(this.j,270).Tc(this)}
function yTd(){tTd=new wTd;n6c((k6c(),j6c),14);!!$stats&&$stats(c7c(xNf,Mbf,-1,-1));tTd.Oe();!!$stats&&$stats(c7c(xNf,Sxf,-1,-1))}
function vTd(){var b,d,e;while(rTd){d=s4c;e=rTd;rTd=rTd.c;!rTd&&(sTd=null);if(!d){NP(e.b)}else{try{NP(e.b)}catch(b){b=dQd(b);if(!Tgd(b,209))throw b}}}}
function TM(b){var c;!b.xc&&(b.xc=(c=vI((!b.Gc&&(b.Gc=new zhe),b.Gc),(!b.yc&&(b.yc=new i$c),b.yc),(!b.wc&&(b.wc=new ZZc),b.wc),!b.Fc&&(b.Fc=(new qge).af(new _fe,new dge))),c.Mc(),c));return b.xc}
function zYc(){var b,c,d,e,f,g,i,j;if(xYc){return xYc}else{xYc=new MZc;MYc(xYc,_Mf,aNf,false);g=new Dme;g.M[bNf]=(Nue(),Jue).b;g.M[cNf]=(_ue(),Xue).b;b=new Dme;b.M[bNf]=Hue.b;b.M[cNf]=Xue.b;j=new Dme;j.M[bNf]=Lue.b;j.M[cNf]=Xue.b;i=new Dme;i.M[bNf]=Kue.b;i.M[cNf]=Xue.b;PYc(xYc,dNf,Cgd(bPd,{267:1,317:1},105,[g,b,j,i]));c=new Mne(eNf,fNf);HBe(c.M,lxf,(qOe(),qOe(),pOe));d=new Mne(gNf,hNf);d.M[iNf]=jNf;e=new Mne(kNf,lNf);f=new Mne(mNf,nNf);mZc(xYc,Cgd(_Od,{267:1,317:1},103,[c,d,e,f]));MYc(xYc,oNf,o7c()+pNf,false);MYc(xYc,qNf,o7c()+rNf,false);return xYc}}
function i$c(){var b,c,d,e,i,n,q,t,w,x,y,z,A;this.b=new qtb;d=new JCe;Bgb(d,v7e,(iye(),cye).b,true);Fgb(d,H7e,dQe(2));Agb(d)?(i=d.cd(),i.setProperty(g6e,d6e),undefined):(d.o[g6e]=d6e,undefined);Agb(d)?(n=d.cd(),n.setProperty(c6e,20),undefined):(d.o[c6e]=20,undefined);Agb(d)?(q=d.cd(),q.setProperty(s7e,sNf),undefined):(d.o[s7e]=sNf,undefined);c=new xCe(tNf);nhb(c,new n$c);e=new $Me;b=new eNe;Agb(b)?(t=b.cd(),t.setProperty(Axf,Bxf),undefined):(b.o[Axf]=Bxf,undefined);Agb(b)?(w=b.cd(),w.setProperty(Cxf,Zff),undefined):(b.o[Cxf]=Zff,undefined);nhb(b,new x$c(this));YMe(e,b);htb(this.b,Cgd(FPd,{267:1,317:1},137,[d,c,e,(this.c=new Tib,Ghb(this.c),Chb(this.c),Hgb(this.c,vyf,(qOe(),qOe(),pOe),true),Egb(this.c,sxf,0,true),x=new CJe(eNf),y=new CJe(gNf),z=new CJe(kNf),A=new CJe(mNf),Dgb(this.c,rxf,Cgd(KPd,{267:1,317:1},190,[x,y,z,A]),true),Hgb(this.c,Hxf,pOe,true),Hgb(this.c,Mxf,pOe,true),Ggb(this.c,qxf,KYc(zYc())),Hgb(this.c,Gxf,pOe,false),Egb(this.c,sxf,0,true),Hgb(this.c,Gxf,pOe,false),Hgb(this.c,Ixf,pOe,true),Hgb(this.c,uNf,pOe,true),this.c)]))}
var aNf='/response/data/recordlist/*',sNf='<span style="font-size:14px;font-weight:bold;">Test Rest Data Source<\/span>',GNf='AsyncLoader14',vNf='DATA',fNf='Data 1',hNf='Data 2',lNf='Data 3',nNf='Data 4',tNf='Test RPC',zNf='TestRestDataSourceData$1',ANf='TestRestDataSourcePresenter',rNf='TestRestDataSourceServlet?method=add',pNf='TestRestDataSourceServlet?method=fetch',wNf='TestRestDataSourceServlet?method=rpc',CNf='TestRestDataSourceView',DNf='TestRestDataSourceView$1',ENf='TestRestDataSourceView$1$1',FNf='TestRestDataSourceView$2',yNf='com.gdn.venice.client.app.testrestdatasource.data.',BNf='com.gdn.venice.client.app.testrestdatasource.view.',eNf='data1',gNf='data2',jNf='data2/name',kNf='data3',mNf='data4',xNf='runCallbacks14',iNf='valueXPath';var xYc=null;_=MZc.prototype=AYc.prototype=new BYc;_.gC=function NZc(){return QEd};_.qe=function OZc(b){var c;return c=this.rd(),c.__transformRequest(b.cd())};_.re=function PZc(b,c,d){var e;e=this.rd();e.__transformResponse(b.cd(),c.cd(),d)};_.cM={87:1,217:1,314:1};_=SZc.prototype=QZc.prototype=new FW;_.gC=function TZc(){return TEd};_.Oc=function UZc(){yhe(this.g,this,new xke((g_c(),e_c),this))};_.cM={87:1,304:1};_=i$c.prototype=f$c.prototype=new qY;_.Uc=function j$c(){return this.b};_.gC=function k$c(){return XEd};_.cM={270:1};_.b=null;_.c=null;_=n$c.prototype=l$c.prototype=new jH;_.gC=function o$c(){return VEd};_.Vc=function p$c(b){var c;c=new Ule;c.M[V6e]=vNf;c.M[W6e]=o7c()+wNf;c.M[Y6e]=Z6e;HBe(c.M,$6e,(qOe(),qOe(),pOe));HBe(c.M,_6e,oOe);Ate(c,new s$c)};_.cM={287:1,319:1};_=s$c.prototype=q$c.prototype=new jH;_.Pc=function t$c(b,c,d){$wnd.isc.say(xzf)};_.gC=function u$c(){return UEd};_.cM={};_=x$c.prototype=v$c.prototype=new jH;_.gC=function y$c(){return WEd};_.Vc=function z$c(b){var c;c=this.b.c.rd();c.startEditingNew()};_.cM={287:1,319:1};_.b=null;_=wTd.prototype=qTd.prototype=new jH;_.gC=function xTd(){return XGd};_.Oe=function BTd(){vTd()};_.cM={};var QEd=HOe(yNf,zNf),TEd=HOe(eof,ANf),XEd=HOe(BNf,CNf),VEd=HOe(BNf,DNf),UEd=HOe(BNf,ENf),WEd=HOe(BNf,FNf),XGd=HOe(Xrf,GNf);$entry(yTd)();