function bOc(){}
function OPc(){}
function UPc(){}
function kUd(){}
function eUd(){}
function hQ(b){b.c.We(QM(b.b.b))}
function WPc(){lgb();Tib.call(this)}
function dOc(b,c,d){aX.call(this,b,c);this.d=d;Qgd(this.j,260).Tc(this);Qgd(Qgd(this.j,260).Uc(),3).b=Qgd(this.d,261).Qc()}
function mUd(){hUd=new kUd;n6c((k6c(),j6c),16);!!$stats&&$stats(c7c(jOf,Mbf,-1,-1));hUd.Oe();!!$stats&&$stats(c7c(jOf,Sxf,-1,-1))}
function jUd(){var b,d,e;while(fUd){d=s4c;e=fUd;fUd=fUd.c;!fUd&&(gUd=null);if(!d){hQ(e.b)}else{try{hQ(e.b)}catch(b){b=dQd(b);if(!Tgd(b,209))throw b}}}}
function QM(b){var c;!b.nc&&(b.nc=(c=new dOc((!b.Gc&&(b.Gc=new zhe),b.Gc),(!b.tc&&(b.tc=new RPc),b.tc),(!b.mc&&(b.mc=new kOc),b.mc)),c.Mc(),c));return b.nc}
function INc(){var b,c,d;if(GNc){return GNc}else{GNc=new pZc;GNc.pe(bOf);b=new Mne(S5e,rLf);HBe(b.M,lxf,(qOe(),qOe(),pOe));d=new Mne(uyf,cOf);c=new Mne(obf,dOf);mZc(GNc,Cgd(_Od,{267:1,317:1},103,[b,d,c]));GNc.oe(eOf);NYc(GNc,fOf,pOe,false);return GNc}}
function RPc(){var b,c,d,e,f,g,i,j;this.b=new M3c;htb(this.b,Cgd(FPd,{267:1,317:1},137,[(e=new WPc,Agb(e)?(g=e.cd(),g.setProperty(g6e,d6e),undefined):(e.o[g6e]=d6e,undefined),Agb(e)?(i=e.cd(),i.setProperty(c6e,d6e),undefined):(e.o[c6e]=d6e,undefined),Hgb(e,vyf,(qOe(),qOe(),pOe),true),Hgb(e,gMf,pOe,true),Eib(e,pOe),Agb(e)?(j=e.cd(),j.setProperty(sxf,0),undefined):(e.o[sxf]=0,undefined),b=new FJe(S5e,rLf,100),f=new EJe(uyf,cOf),c=new EJe(obf,dOf),d=new FJe(gOf,hOf,200),Agb(e)?Pgb(e,rxf,SAe(Cgd(KPd,{267:1,317:1},190,[b,f,c,d]))):(e.o[rxf]=SAe(Cgd(KPd,{267:1,317:1},190,[b,f,c,d])),undefined),Hgb(e,Hxf,pOe,true),Hgb(e,Mxf,pOe,true),Ggb(e,qxf,KYc(INc())),Hgb(e,Gxf,pOe,false),Agb(e)?undefined:(e.o[wHf]=uyf,undefined),Cgb(e,(wwe(),twe)),Hgb(e,Ixf,pOe,true),Hgb(e,uNf,pOe,true),e)]))}
var bOf='/tasklaunchpad/tasks/task',oOf='AsyncLoader16',hOf='Start',kOf='TaskLaunchpadPresenter',mOf='TaskLaunchpadView',nOf='TaskLaunchpadView$1',iOf='[SKIN]/icons/play.png',eOf='ds/test_data/tasklaunchpad.data.xml',jOf='runCallbacks16',gOf='startField';var GNc=null;_=dOc.prototype=bOc.prototype=new FW;_.gC=function eOc(){return bDd};_.Oc=function fOc(){yhe(this.g,this,new xke((g_c(),e_c),this))};_.cM={87:1,304:1};_=RPc.prototype=OPc.prototype=new qY;_.Uc=function SPc(){return this.b};_.gC=function TPc(){return qDd};_.cM={260:1};_.b=null;_=WPc.prototype=UPc.prototype=new Rfb;_.Dd=function XPc(b,c){var d,e,i,n,q,t;e=kib(this,c.b);if(fRe(e,gOf)){d=new cDe;Agb(d)?(i=d.cd(),i.setProperty(c6e,18),undefined):(d.o[c6e]=18,undefined);Agb(d)?(n=d.cd(),n.setProperty(g6e,65),undefined):(d.o[g6e]=65,undefined);Agb(d)?(q=d.cd(),q.setProperty(Axf,iOf),undefined):(d.o[Axf]=iOf,undefined);Agb(d)?(t=d.cd(),t.setProperty(pbf,hOf),undefined):(d.o[pbf]=hOf,undefined);return d}else{return null}};_.gC=function YPc(){return pDd};_.cM={69:1,86:1,87:1,91:1,93:1,94:1,95:1,136:1,137:1,138:1,139:1,140:1,141:1,142:1,143:1,144:1,145:1,146:1,147:1,148:1,149:1,150:1,151:1,152:1,153:1,154:1,155:1,156:1,157:1,158:1,159:1,160:1,161:1,162:1,163:1,164:1,165:1,166:1,167:1,168:1,169:1,192:1,195:1,196:1,197:1};_=kUd.prototype=eUd.prototype=new jH;_.gC=function lUd(){return bHd};_.Oe=function pUd(){jUd()};_.cM={};var bDd=HOe(Vnf,kOf),qDd=HOe(lOf,mOf),pDd=HOe(lOf,nOf),bHd=HOe(Xrf,oOf);$entry(mUd)();