function U7(){}
function $7(){}
function $mb(){}
function Kmb(){}
function Qmb(){}
function Vmb(){}
function L2d(){}
function F2d(){}
function a8(b){this.b=b}
function anb(b){this.b=b}
function Smb(b){this.b=b}
function Xmb(b){this.b=b}
function fV(b){b.c.We(jM(b.b.b))}
function RH(b,c,d){return new X7(b,c,d)}
function N2d(){I2d=new L2d;n6c((k6c(),j6c),40);!!$stats&&$stats(c7c(Jig,Mbf,-1,-1));I2d.Oe();!!$stats&&$stats(c7c(Jig,Sxf,-1,-1))}
function X7(b,c,d){aX.call(this,b,c);this.d=d;Qgd(this.j,15).Tc(this);Qgd(Qgd(this.j,15).Uc(),3).b=Qgd(this.d,16).Qc();Fwb(Qgd(this.j,15).d,X4())}
function K2d(){var b,d,e;while(G2d){d=s4c;e=G2d;G2d=G2d.c;!G2d&&(H2d=null);if(!d){fV(e.b)}else{try{fV(e.b)}catch(b){b=dQd(b);if(!Tgd(b,209))throw b}}}}
function jM(b){var c;!b.t&&(b.t=(c=RH((!b.Gc&&(b.Gc=new zhe),b.Gc),(!b.K&&(b.K=new Nmb),b.K),(!b.s&&(b.s=new h8),b.s),!b.Fc&&(b.Fc=(new qge).af(new _fe,new dge))),c.Mc(),c));return b.t}
function W7(b,c){var d,e,f,g;g=new Ule;f=new KZe;for(e=0;e<c.c;++e){f.il(M1f+(e+1),Qgd((SWe(e,c.c),c.b[e]),1))}d=gVe(f);g.M[V6e]=d;g.M[W6e]=o7c()+Fig;g.M[Y6e]=Z6e;HBe(g.M,$6e,(qOe(),qOe(),pOe));HBe(g.M,nBf,pOe);$wnd.isc.RPCManager.addClassProperties({promptStyle:(Cye(),Bye).Nk()});LAe();$wnd.isc.RPCManager.defaultPrompt=Gig;$wnd.isc.RPCManager.showPrompt=true;Ate(g,new a8(b))}
function Nmb(){var b,e,f,g;this.c=new M3c;b=new $Me;Agb(b)?(e=b.cd(),e.setProperty(g6e,d6e),undefined):(b.o[g6e]=d6e,undefined);Fgb(b,H7e,dQe(2));this.f=new eNe;Bgb(this.f,Axf,XHf,true);Dhb(this.f,LYf);Bgb(this.f,pbf,ZHf,true);f=this.f.rd();f.disable();YMe(b,this.f);this.e=new eNe;Bgb(this.e,Axf,Bzf,true);Dhb(this.e,Hig);Bgb(this.e,pbf,mif,true);YMe(b,this.e);this.b=new eNe;Bgb(this.b,Axf,UBf,true);Dhb(this.b,EKf);Bgb(this.b,pbf,kaf,true);g=this.b.rd();g.disable();YMe(b,this.b);this.d=new Kwb(this);htb(this.c,Cgd(FPd,{267:1,317:1},137,[b,this.d]));nhb(this.f,new Smb(this));nhb(this.b,new Xmb(this));nhb(this.e,new anb(this));Bwb(this.d)}
var Qig='AsyncLoader40',Kig='JournalPresenter',Lig='JournalPresenter$1',Fig='JournalPresenterServlet?method=submitJournalForApproval&type=RPC',Mig='JournalView',Nig='JournalView$1',Oig='JournalView$2',Pig='JournalView$3',Hig='Print Journal Details',Gig='Submitting journals for approval...',Iig='Venice/JournalReportLauncherServlet?journalGroupId=',Jig='runCallbacks40';_=X7.prototype=U7.prototype=new FW;_.gC=function Y7(){return ald};_.Oc=function Z7(){yhe(this.g,this,new xke((g_c(),e_c),this))};_.cM={35:1,87:1,304:1};_=a8.prototype=$7.prototype=new jH;_.Pc=function b8(b,c,d){var e,f;e=c.tM==n0e||c.cM&&!!c.cM[1]?c.tS():c.toString?c.toString():Z5e;if(e.indexOf(Kcf)==0){Gwb(Qgd(Qgd(this.b.j,15),17).d);$wnd.isc.say(tHf)}else{f=qRe(e,c7e,0);f.length>1?oCe(f[1],null):oCe(xzf,null)}LAe();$wnd.isc.RPCManager.defaultPrompt=DBf;$wnd.isc.RPCManager.showPrompt=false};_.gC=function c8(){return Zkd};_.cM={};_.b=null;_=Nmb.prototype=Kmb.prototype=new qY;_.Uc=function Omb(){return this.c};_.gC=function Pmb(){return Wmd};_.cM={15:1,17:1};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_=Smb.prototype=Qmb.prototype=new jH;_.gC=function Tmb(){return Tmd};_.Vc=function Umb(b){var c,d,e,f,g,i;e=(f=this.b.d.f.rd(),g=f.getSelection(),Xib(g));d=new xYe;for(c=0;c<e.length;++c){kYe(d,(i=e[c].M[rBf],i===undefined||i==null?null:String(i)))}W7(Qgd(this.b.A,35),d)};_.cM={287:1,319:1};_.b=null;_=Xmb.prototype=Vmb.prototype=new jH;_.gC=function Ymb(){return Umd};_.Vc=function Zmb(b){var c,d,e,f,g,i;e=(f=this.b.d.f.rd(),g=f.getSelection(),Xib(g));d=(i=e[0].M[rBf],i===undefined||i==null?null:String(i));c=o7c();c.indexOf(WCf)!=-1&&(c=XCf);c.indexOf(YCf)!=-1&&(c=c.substr(0,c.indexOf(YCf)-0));$wnd.open(c+Iig+d,qCf,null)};_.cM={287:1,319:1};_.b=null;_=anb.prototype=$mb.prototype=new jH;_.gC=function bnb(){return Vmd};_.Vc=function cnb(b){U0c(this.b.d)};_.cM={287:1,319:1};_.b=null;_=L2d.prototype=F2d.prototype=new jH;_.gC=function M2d(){return CId};_.Oe=function Q2d(){K2d()};_.cM={};var ald=HOe(vmf,Kig),Zkd=HOe(vmf,Lig),Wmd=HOe(yyf,Mig),Tmd=HOe(yyf,Nig),Umd=HOe(yyf,Oig),Vmd=HOe(yyf,Pig),CId=HOe(Xrf,Qig);$entry(N2d)();