function AYc(){}
function QZc(){}
function f$c(){}
function n$c(){}
function l$c(){}
function s$c(){}
function q$c(){}
function v$c(){}
function uTd(){}
function oTd(){}
function x$c(b){this.b=b}
function MZc(){GZc.call(this)}
function NP(b){b.c.We(TM(b.b.b))}
function vI(b,c,d){return new SZc(b,c,d)}
function SZc(b,c,d){aX.call(this,b,c);this.d=d;Ogd(this.j,270).Tc(this)}
function wTd(){rTd=new uTd;n6c((k6c(),j6c),14);!!$stats&&$stats(c7c(BNf,Nbf,-1,-1));rTd.Oe();!!$stats&&$stats(c7c(BNf,Wxf,-1,-1))}
function tTd(){var b,d,e;while(pTd){d=s4c;e=pTd;pTd=pTd.c;!pTd&&(qTd=null);if(!d){NP(e.b)}else{try{NP(e.b)}catch(b){b=bQd(b);if(!Rgd(b,209))throw b}}}}
function TM(b){var c;!b.xc&&(b.xc=(c=vI((!b.Gc&&(b.Gc=new Ahe),b.Gc),(!b.yc&&(b.yc=new i$c),b.yc),(!b.wc&&(b.wc=new ZZc),b.wc),!b.Fc&&(b.Fc=(new rge).af(new age,new ege))),c.Mc(),c));return b.xc}
function zYc(){var b,c,d,e,f,g,i,j;if(xYc){return xYc}else{xYc=new MZc;MYc(xYc,dNf,eNf,false);g=new Eme;g.M[fNf]=(Oue(),Kue).b;g.M[gNf]=(ave(),Yue).b;b=new Eme;b.M[fNf]=Iue.b;b.M[gNf]=Yue.b;j=new Eme;j.M[fNf]=Mue.b;j.M[gNf]=Yue.b;i=new Eme;i.M[fNf]=Lue.b;i.M[gNf]=Yue.b;PYc(xYc,hNf,Agd(_Od,{267:1,317:1},105,[g,b,j,i]));c=new Nne(iNf,jNf);IBe(c.M,pxf,(rOe(),rOe(),qOe));d=new Nne(kNf,lNf);d.M[mNf]=nNf;e=new Nne(oNf,pNf);f=new Nne(qNf,rNf);mZc(xYc,Agd(ZOd,{267:1,317:1},103,[c,d,e,f]));MYc(xYc,sNf,o7c()+tNf,false);MYc(xYc,uNf,o7c()+vNf,false);return xYc}}
function i$c(){var b,c,d,e,i,n,q,t,w,x,y,z,A;this.b=new qtb;d=new KCe;Bgb(d,w7e,(jye(),dye).b,true);Fgb(d,I7e,eQe(2));Agb(d)?(i=d.cd(),i.setProperty(h6e,e6e),undefined):(d.o[h6e]=e6e,undefined);Agb(d)?(n=d.cd(),n.setProperty(d6e,20),undefined):(d.o[d6e]=20,undefined);Agb(d)?(q=d.cd(),q.setProperty(t7e,wNf),undefined):(d.o[t7e]=wNf,undefined);c=new yCe(xNf);nhb(c,new n$c);e=new _Me;b=new fNe;Agb(b)?(t=b.cd(),t.setProperty(Exf,Fxf),undefined):(b.o[Exf]=Fxf,undefined);Agb(b)?(w=b.cd(),w.setProperty(Gxf,bgf),undefined):(b.o[Gxf]=bgf,undefined);nhb(b,new x$c(this));ZMe(e,b);htb(this.b,Agd(DPd,{267:1,317:1},137,[d,c,e,(this.c=new Tib,Ghb(this.c),Chb(this.c),Hgb(this.c,zyf,(rOe(),rOe(),qOe),true),Egb(this.c,wxf,0,true),x=new DJe(iNf),y=new DJe(kNf),z=new DJe(oNf),A=new DJe(qNf),Dgb(this.c,vxf,Agd(IPd,{267:1,317:1},190,[x,y,z,A]),true),Hgb(this.c,Lxf,qOe,true),Hgb(this.c,Qxf,qOe,true),Ggb(this.c,uxf,KYc(zYc())),Hgb(this.c,Kxf,qOe,false),Egb(this.c,wxf,0,true),Hgb(this.c,Kxf,qOe,false),Hgb(this.c,Mxf,qOe,true),Hgb(this.c,yNf,qOe,true),this.c)]))}
var eNf='/response/data/recordlist/*',wNf='<span style="font-size:14px;font-weight:bold;">Test Rest Data Source<\/span>',KNf='AsyncLoader14',zNf='DATA',jNf='Data 1',lNf='Data 2',pNf='Data 3',rNf='Data 4',xNf='Test RPC',DNf='TestRestDataSourceData$1',ENf='TestRestDataSourcePresenter',vNf='TestRestDataSourceServlet?method=add',tNf='TestRestDataSourceServlet?method=fetch',ANf='TestRestDataSourceServlet?method=rpc',GNf='TestRestDataSourceView',HNf='TestRestDataSourceView$1',INf='TestRestDataSourceView$1$1',JNf='TestRestDataSourceView$2',CNf='com.gdn.venice.client.app.testrestdatasource.data.',FNf='com.gdn.venice.client.app.testrestdatasource.view.',iNf='data1',kNf='data2',nNf='data2/name',oNf='data3',qNf='data4',BNf='runCallbacks14',mNf='valueXPath';var xYc=null;_=MZc.prototype=AYc.prototype=new BYc;_.gC=function NZc(){return OEd};_.qe=function OZc(b){var c;return c=this.rd(),c.__transformRequest(b.cd())};_.re=function PZc(b,c,d){var e;e=this.rd();e.__transformResponse(b.cd(),c.cd(),d)};_.cM={87:1,217:1,314:1};_=SZc.prototype=QZc.prototype=new FW;_.gC=function TZc(){return REd};_.Oc=function UZc(){zhe(this.g,this,new yke((g_c(),e_c),this))};_.cM={87:1,304:1};_=i$c.prototype=f$c.prototype=new qY;_.Uc=function j$c(){return this.b};_.gC=function k$c(){return VEd};_.cM={270:1};_.b=null;_.c=null;_=n$c.prototype=l$c.prototype=new jH;_.gC=function o$c(){return TEd};_.Vc=function p$c(b){var c;c=new Vle;c.M[W6e]=zNf;c.M[X6e]=o7c()+ANf;c.M[Z6e]=$6e;IBe(c.M,_6e,(rOe(),rOe(),qOe));IBe(c.M,a7e,pOe);Bte(c,new s$c)};_.cM={287:1,319:1};_=s$c.prototype=q$c.prototype=new jH;_.Pc=function t$c(b,c,d){$wnd.isc.say(Bzf)};_.gC=function u$c(){return SEd};_.cM={};_=x$c.prototype=v$c.prototype=new jH;_.gC=function y$c(){return UEd};_.Vc=function z$c(b){var c;c=this.b.c.rd();c.startEditingNew()};_.cM={287:1,319:1};_.b=null;_=uTd.prototype=oTd.prototype=new jH;_.gC=function vTd(){return VGd};_.Oe=function zTd(){tTd()};_.cM={};var OEd=IOe(CNf,DNf),REd=IOe(iof,ENf),VEd=IOe(FNf,GNf),TEd=IOe(FNf,HNf),SEd=IOe(FNf,INf),UEd=IOe(FNf,JNf),VGd=IOe(_rf,KNf);$entry(wTd)();