function U7(){}
function $7(){}
function $mb(){}
function Kmb(){}
function Qmb(){}
function Vmb(){}
function J2d(){}
function D2d(){}
function a8(b){this.b=b}
function anb(b){this.b=b}
function Smb(b){this.b=b}
function Xmb(b){this.b=b}
function fV(b){b.c.We(jM(b.b.b))}
function RH(b,c,d){return new X7(b,c,d)}
function L2d(){G2d=new J2d;n6c((k6c(),j6c),40);!!$stats&&$stats(c7c(Nig,Nbf,-1,-1));G2d.Oe();!!$stats&&$stats(c7c(Nig,Wxf,-1,-1))}
function X7(b,c,d){aX.call(this,b,c);this.d=d;Ogd(this.j,15).Tc(this);Ogd(Ogd(this.j,15).Uc(),3).b=Ogd(this.d,16).Qc();Fwb(Ogd(this.j,15).d,X4())}
function I2d(){var b,d,e;while(E2d){d=s4c;e=E2d;E2d=E2d.c;!E2d&&(F2d=null);if(!d){fV(e.b)}else{try{fV(e.b)}catch(b){b=bQd(b);if(!Rgd(b,209))throw b}}}}
function jM(b){var c;!b.t&&(b.t=(c=RH((!b.Gc&&(b.Gc=new Ahe),b.Gc),(!b.K&&(b.K=new Nmb),b.K),(!b.s&&(b.s=new h8),b.s),!b.Fc&&(b.Fc=(new rge).af(new age,new ege))),c.Mc(),c));return b.t}
function W7(b,c){var d,e,f,g;g=new Vle;f=new LZe;for(e=0;e<c.c;++e){f.il(Q1f+(e+1),Ogd((TWe(e,c.c),c.b[e]),1))}d=hVe(f);g.M[W6e]=d;g.M[X6e]=o7c()+Jig;g.M[Z6e]=$6e;IBe(g.M,_6e,(rOe(),rOe(),qOe));IBe(g.M,rBf,qOe);$wnd.isc.RPCManager.addClassProperties({promptStyle:(Dye(),Cye).Nk()});MAe();$wnd.isc.RPCManager.defaultPrompt=Kig;$wnd.isc.RPCManager.showPrompt=true;Bte(g,new a8(b))}
function Nmb(){var b,e,f,g;this.c=new M3c;b=new _Me;Agb(b)?(e=b.cd(),e.setProperty(h6e,e6e),undefined):(b.o[h6e]=e6e,undefined);Fgb(b,I7e,eQe(2));this.f=new fNe;Bgb(this.f,Exf,_Hf,true);Dhb(this.f,PYf);Bgb(this.f,qbf,bIf,true);f=this.f.rd();f.disable();ZMe(b,this.f);this.e=new fNe;Bgb(this.e,Exf,Fzf,true);Dhb(this.e,Lig);Bgb(this.e,qbf,qif,true);ZMe(b,this.e);this.b=new fNe;Bgb(this.b,Exf,YBf,true);Dhb(this.b,IKf);Bgb(this.b,qbf,laf,true);g=this.b.rd();g.disable();ZMe(b,this.b);this.d=new Kwb(this);htb(this.c,Agd(DPd,{267:1,317:1},137,[b,this.d]));nhb(this.f,new Smb(this));nhb(this.b,new Xmb(this));nhb(this.e,new anb(this));Bwb(this.d)}
var Uig='AsyncLoader40',Oig='JournalPresenter',Pig='JournalPresenter$1',Jig='JournalPresenterServlet?method=submitJournalForApproval&type=RPC',Qig='JournalView',Rig='JournalView$1',Sig='JournalView$2',Tig='JournalView$3',Lig='Print Journal Details',Kig='Submitting journals for approval...',Mig='Venice/JournalReportLauncherServlet?journalGroupId=',Nig='runCallbacks40';_=X7.prototype=U7.prototype=new FW;_.gC=function Y7(){return $kd};_.Oc=function Z7(){zhe(this.g,this,new yke((g_c(),e_c),this))};_.cM={35:1,87:1,304:1};_=a8.prototype=$7.prototype=new jH;_.Pc=function b8(b,c,d){var e,f;e=c.tM==o0e||c.cM&&!!c.cM[1]?c.tS():c.toString?c.toString():$5e;if(e.indexOf(Mcf)==0){Gwb(Ogd(Ogd(this.b.j,15),17).d);$wnd.isc.say(xHf)}else{f=rRe(e,d7e,0);f.length>1?pCe(f[1],null):pCe(Bzf,null)}MAe();$wnd.isc.RPCManager.defaultPrompt=HBf;$wnd.isc.RPCManager.showPrompt=false};_.gC=function c8(){return Xkd};_.cM={};_.b=null;_=Nmb.prototype=Kmb.prototype=new qY;_.Uc=function Omb(){return this.c};_.gC=function Pmb(){return Umd};_.cM={15:1,17:1};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_=Smb.prototype=Qmb.prototype=new jH;_.gC=function Tmb(){return Rmd};_.Vc=function Umb(b){var c,d,e,f,g,i;e=(f=this.b.d.f.rd(),g=f.getSelection(),Xib(g));d=new yYe;for(c=0;c<e.length;++c){lYe(d,(i=e[c].M[vBf],i===undefined||i==null?null:String(i)))}W7(Ogd(this.b.A,35),d)};_.cM={287:1,319:1};_.b=null;_=Xmb.prototype=Vmb.prototype=new jH;_.gC=function Ymb(){return Smd};_.Vc=function Zmb(b){var c,d,e,f,g,i;e=(f=this.b.d.f.rd(),g=f.getSelection(),Xib(g));d=(i=e[0].M[vBf],i===undefined||i==null?null:String(i));c=o7c();c.indexOf($Cf)!=-1&&(c=_Cf);c.indexOf(aDf)!=-1&&(c=c.substr(0,c.indexOf(aDf)-0));$wnd.open(c+Mig+d,uCf,null)};_.cM={287:1,319:1};_.b=null;_=anb.prototype=$mb.prototype=new jH;_.gC=function bnb(){return Tmd};_.Vc=function cnb(b){U0c(this.b.d)};_.cM={287:1,319:1};_.b=null;_=J2d.prototype=D2d.prototype=new jH;_.gC=function K2d(){return AId};_.Oe=function O2d(){I2d()};_.cM={};var $kd=IOe(zmf,Oig),Xkd=IOe(zmf,Pig),Umd=IOe(Cyf,Qig),Rmd=IOe(Cyf,Rig),Smd=IOe(Cyf,Sig),Tmd=IOe(Cyf,Tig),AId=IOe(_rf,Uig);$entry(L2d)();