function MNc(){}
function IPc(){}
function IZd(){}
function OZd(){}
function US(b){b.c.Xe(PM(b.b.b))}
function uI(b,c,d){return new ONc(b,c,d)}
function _ne(){Fme.call(this,(Bwe(),zwe))}
function Fme(b){this.M=new Object;this.M[Gbf]=Abg;this.M[rzf]=b.b}
function ONc(b,c,d){aX.call(this,b,c);this.d=d;Wgd(this.j,258).Tc(this);Wgd(Wgd(this.j,258).Uc(),3).b=Wgd(this.d,259).Qc()}
function QZd(){LZd=new OZd;m6c((j6c(),i6c),29);!!$stats&&$stats(b7c(Dbg,ccf,-1,-1));LZd.Pe();!!$stats&&$stats(b7c(Dbg,Pyf,-1,-1))}
function NZd(){var b,d,e;while(JZd){d=s4c;e=JZd;JZd=JZd.c;!JZd&&(KZd=null);if(!d){US(e.b)}else{try{US(e.b)}catch(b){b=jQd(b);if(!Zgd(b,209))throw b}}}}
function PM(b){var c;!b.lc&&(b.lc=(c=uI((!b.Gc&&(b.Gc=new Phe),b.Gc),(!b.sc&&(b.sc=new LPc),b.sc),(!b.kc&&(b.kc=new VNc),b.kc),!b.Fc&&(b.Fc=(new Gge).cf(new pge,new tge))),c.Mc(),c));return b.lc}
function ENc(){var b,c,d,e,f,g,i;if(CNc){return CNc}else{CNc=new pZc;CNc.pe(ubg);c=new _ne;XBe(c.M,iyf,(GOe(),GOe(),FOe));i=new aoe(rzf,_Of);f=new aoe(vbg,dyf);b=new aoe(wbg,f_f);e=new Pne(xbg,h_f);g=new Pne(ybg,j_f);d=new aoe(Kyf,JOf);mZc(CNc,Igd(fPd,{267:1,317:1},103,[c,i,f,b,e,g,d]));CNc.oe(zbg);NYc(CNc,cPf,FOe,false);return CNc}}
function LPc(){var b,c,d,e,f,g,i,j,k,n;this.b=new M3c;htb(this.b,Igd(LPd,{267:1,317:1},137,[(b=new Tib,Agb(b)?(j=b.cd(),j.setProperty(x6e,u6e),undefined):(b.o[x6e]=u6e,undefined),Agb(b)?(k=b.cd(),k.setProperty(t6e,u6e),undefined):(b.o[t6e]=u6e,undefined),Hgb(b,szf,(GOe(),GOe(),FOe),true),Agb(b)?(n=b.cd(),n.setProperty(pyf,0),undefined):(b.o[pyf]=0,undefined),f=new VJe(Abg,oMf,100),i=new VJe(rzf,_Of,200),i.M[vAf]=gBe(Igd($Pd,{267:1,317:1,318:1},1,[Bbg,Cbg])),d=new VJe(vbg,dyf,400),c=new VJe(xbg,h_f,100),e=new VJe(ybg,j_f,100),g=new UJe(Kyf,JOf),Agb(b)?Pgb(b,oyf,gBe(Igd(QPd,{267:1,317:1},190,[f,i,d,c,e,g]))):(b.o[oyf]=gBe(Igd(QPd,{267:1,317:1},190,[f,i,d,c,e,g])),undefined),Hgb(b,Eyf,FOe,true),Hgb(b,Jyf,FOe,true),Ggb(b,nyf,KYc(ENc())),Hgb(b,Dyf,FOe,false),Agb(b)?undefined:(b.o[tIf]=rzf,undefined),Cgb(b,(Mwe(),Jwe)),Hgb(b,Fyf,FOe,true),Hgb(b,rOf,FOe,true),b)]))}
var ubg='/assignedtask/tasks/task',Ebg='AssignedTaskPresenter',Fbg='AssignedTaskView',Gbg='AsyncLoader29',Bbg='Human Resources - Recruitment',Cbg='Human Resources - Travel Management',wbg='assignee',zbg='ds/test_data/assignedtask.data.xml',Dbg='runCallbacks29',xbg='taskdate',vbg='taskdesc',ybg='taskduedate',Abg='taskid';var CNc=null;_=ONc.prototype=MNc.prototype=new FW;_.gC=function PNc(){return eDd};_.Oc=function QNc(){Ohe(this.g,this,new Nke((g_c(),e_c),this))};_.cM={87:1,304:1};_=LPc.prototype=IPc.prototype=new qY;_.Uc=function MPc(){return this.b};_.gC=function NPc(){return uDd};_.cM={258:1};_.b=null;_=OZd.prototype=IZd.prototype=new jH;_.gC=function PZd(){return WHd};_.Pe=function TZd(){NZd()};_.cM={};_=_ne.prototype=Zne.prototype;var eDd=XOe(Sof,Ebg),uDd=XOe(iPf,Fbg),WHd=XOe(Tsf,Gbg);$entry(QZd)();