function U7(){}
function $7(){}
function $mb(){}
function Kmb(){}
function Qmb(){}
function Vmb(){}
function R2d(){}
function L2d(){}
function a8(b){this.b=b}
function anb(b){this.b=b}
function Smb(b){this.b=b}
function Xmb(b){this.b=b}
function fV(b){b.c.Xe(jM(b.b.b))}
function RH(b,c,d){return new X7(b,c,d)}
function T2d(){O2d=new R2d;m6c((j6c(),i6c),40);!!$stats&&$stats(b7c(Gjg,ccf,-1,-1));O2d.Pe();!!$stats&&$stats(b7c(Gjg,Pyf,-1,-1))}
function X7(b,c,d){aX.call(this,b,c);this.d=d;Wgd(this.j,15).Tc(this);Wgd(Wgd(this.j,15).Uc(),3).b=Wgd(this.d,16).Qc();Fwb(Wgd(this.j,15).d,X4())}
function Q2d(){var b,d,e;while(M2d){d=s4c;e=M2d;M2d=M2d.c;!M2d&&(N2d=null);if(!d){fV(e.b)}else{try{fV(e.b)}catch(b){b=jQd(b);if(!Zgd(b,209))throw b}}}}
function jM(b){var c;!b.t&&(b.t=(c=RH((!b.Gc&&(b.Gc=new Phe),b.Gc),(!b.K&&(b.K=new Nmb),b.K),(!b.s&&(b.s=new h8),b.s),!b.Fc&&(b.Fc=(new Gge).cf(new pge,new tge))),c.Mc(),c));return b.t}
function W7(b,c){var d,e,f,g;g=new ime;f=new $Ze;for(e=0;e<c.c;++e){f.kl(J2f+(e+1),Wgd((gXe(e,c.c),c.b[e]),1))}d=wVe(f);g.M[k7e]=d;g.M[l7e]=n7c()+Cjg;g.M[n7e]=o7e;XBe(g.M,p7e,(GOe(),GOe(),FOe));XBe(g.M,kCf,FOe);$wnd.isc.RPCManager.addClassProperties({promptStyle:(Sye(),Rye).Pk()});_Ae();$wnd.isc.RPCManager.defaultPrompt=Djg;$wnd.isc.RPCManager.showPrompt=true;Qte(g,new a8(b))}
function Nmb(){var b,e,f,g;this.c=new M3c;b=new oNe;Agb(b)?(e=b.cd(),e.setProperty(x6e,u6e),undefined):(b.o[x6e]=u6e,undefined);Fgb(b,Z7e,tQe(2));this.f=new uNe;Bgb(this.f,xyf,UIf,true);Dhb(this.f,IZf);Bgb(this.f,Hbf,WIf,true);f=this.f.rd();f.disable();mNe(b,this.f);this.e=new uNe;Bgb(this.e,xyf,yAf,true);Dhb(this.e,Ejg);Bgb(this.e,Hbf,kjf,true);mNe(b,this.e);this.b=new uNe;Bgb(this.b,xyf,RCf,true);Dhb(this.b,BLf);Bgb(this.b,Hbf,Caf,true);g=this.b.rd();g.disable();mNe(b,this.b);this.d=new Kwb(this);htb(this.c,Igd(LPd,{267:1,317:1},137,[b,this.d]));nhb(this.f,new Smb(this));nhb(this.b,new Xmb(this));nhb(this.e,new anb(this));Bwb(this.d)}
var Njg='AsyncLoader40',Hjg='JournalPresenter',Ijg='JournalPresenter$1',Cjg='JournalPresenterServlet?method=submitJournalForApproval&type=RPC',Jjg='JournalView',Kjg='JournalView$1',Ljg='JournalView$2',Mjg='JournalView$3',Ejg='Print Journal Details',Djg='Submitting journals for approval...',Fjg='Venice/JournalReportLauncherServlet?journalGroupId=',Gjg='runCallbacks40';_=X7.prototype=U7.prototype=new FW;_.gC=function Y7(){return gld};_.Oc=function Z7(){Ohe(this.g,this,new Nke((g_c(),e_c),this))};_.cM={35:1,87:1,304:1};_=a8.prototype=$7.prototype=new jH;_.Pc=function b8(b,c,d){var e,f;e=c.tM==D0e||c.cM&&!!c.cM[1]?c.tS():c.toString?c.toString():o6e;if(e.indexOf(ddf)==0){Gwb(Wgd(Wgd(this.b.j,15),17).d);$wnd.isc.say(qIf)}else{f=GRe(e,t7e,0);f.length>1?ECe(f[1],null):ECe(uAf,null)}_Ae();$wnd.isc.RPCManager.defaultPrompt=ACf;$wnd.isc.RPCManager.showPrompt=false};_.gC=function c8(){return dld};_.cM={};_.b=null;_=Nmb.prototype=Kmb.prototype=new qY;_.Uc=function Omb(){return this.c};_.gC=function Pmb(){return and};_.cM={15:1,17:1};_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_=Smb.prototype=Qmb.prototype=new jH;_.gC=function Tmb(){return Zmd};_.Vc=function Umb(b){var c,d,e,f,g,i;e=(f=this.b.d.f.rd(),g=f.getSelection(),Xib(g));d=new NYe;for(c=0;c<e.length;++c){AYe(d,(i=e[c].M[oCf],i===undefined||i==null?null:String(i)))}W7(Wgd(this.b.A,35),d)};_.cM={287:1,319:1};_.b=null;_=Xmb.prototype=Vmb.prototype=new jH;_.gC=function Ymb(){return $md};_.Vc=function Zmb(b){var c,d,e,f,g,i;e=(f=this.b.d.f.rd(),g=f.getSelection(),Xib(g));d=(i=e[0].M[oCf],i===undefined||i==null?null:String(i));c=n7c();c.indexOf(TDf)!=-1&&(c=UDf);c.indexOf(VDf)!=-1&&(c=c.substr(0,c.indexOf(VDf)-0));$wnd.open(c+Fjg+d,nDf,null)};_.cM={287:1,319:1};_.b=null;_=anb.prototype=$mb.prototype=new jH;_.gC=function bnb(){return _md};_.Vc=function cnb(b){U0c(this.b.d)};_.cM={287:1,319:1};_.b=null;_=R2d.prototype=L2d.prototype=new jH;_.gC=function S2d(){return HId};_.Pe=function W2d(){Q2d()};_.cM={};var gld=XOe(snf,Hjg),dld=XOe(snf,Ijg),and=XOe(vzf,Jjg),Zmd=XOe(vzf,Kjg),$md=XOe(vzf,Ljg),_md=XOe(vzf,Mjg),HId=XOe(Tsf,Njg);$entry(T2d)();